import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "FlavorTown",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="px-5 py-2 flex items-center justify-between gap-5 bg-stone-800">
          <Link href={'/'}><img src="/vercel.svg" alt="" className="w-[120px]" /></Link>
          <div className="space-x-5">
            <Link className="btn" href="/foods">  Food</Link>
            <Link className="btn" href="/reviews">   Reviews  </Link>
          </div>
        </header>

        <main className="p-5">{children}</main>
      </body>
    </html>
  );
}
